/* Generated by Cython 3.1.2 */

#ifndef __PYX_HAVE__CyRK__cy__pysolver_cyhook
#define __PYX_HAVE__CyRK__cy__pysolver_cyhook

#include "Python.h"

/* "CyRK/cy/pysolver_cyhook.pxd":1
 * ctypedef public api void (*DiffeqMethod)(object py_instance) noexcept             # <<<<<<<<<<<<<<
*/

#line 1 "CyRK/cy/pysolver_cyhook.pxd"
typedef void (*DiffeqMethod)(PyObject *);

#line 1 "CyRK/cy/pysolver_cyhook.pxd"


#line 1 "CyRK/cy/pysolver_cyhook.pxd"
#ifndef __PYX_HAVE_API__CyRK__cy__pysolver_cyhook

#line 1 "CyRK/cy/pysolver_cyhook.pxd"


#line 1 "CyRK/cy/pysolver_cyhook.pxd"
#ifdef CYTHON_EXTERN_C

#line 1 "CyRK/cy/pysolver_cyhook.pxd"
    #undef __PYX_EXTERN_C

#line 1 "CyRK/cy/pysolver_cyhook.pxd"
    #define __PYX_EXTERN_C CYTHON_EXTERN_C

#line 1 "CyRK/cy/pysolver_cyhook.pxd"
#elif defined(__PYX_EXTERN_C)

#line 1 "CyRK/cy/pysolver_cyhook.pxd"
    #ifdef _MSC_VER

#line 1 "CyRK/cy/pysolver_cyhook.pxd"
    #pragma message ("Please do not define the '__PYX_EXTERN_C' macro externally. Use 'CYTHON_EXTERN_C' instead.")

#line 1 "CyRK/cy/pysolver_cyhook.pxd"
    #else

#line 1 "CyRK/cy/pysolver_cyhook.pxd"
    #warning Please do not define the '__PYX_EXTERN_C' macro externally. Use 'CYTHON_EXTERN_C' instead.

#line 1 "CyRK/cy/pysolver_cyhook.pxd"
    #endif

#line 1 "CyRK/cy/pysolver_cyhook.pxd"
#else

#line 1 "CyRK/cy/pysolver_cyhook.pxd"
    #define __PYX_EXTERN_C extern "C++"

#line 1 "CyRK/cy/pysolver_cyhook.pxd"
#endif

#line 1 "CyRK/cy/pysolver_cyhook.pxd"


#line 1 "CyRK/cy/pysolver_cyhook.pxd"
#ifndef DL_IMPORT

#line 1 "CyRK/cy/pysolver_cyhook.pxd"
  #define DL_IMPORT(_T) _T

#line 1 "CyRK/cy/pysolver_cyhook.pxd"
#endif

__PYX_EXTERN_C void call_diffeq_from_cython(PyObject *, DiffeqMethod);

#endif /* !__PYX_HAVE_API__CyRK__cy__pysolver_cyhook */

/* WARNING: the interface of the module init function changed in CPython 3.5. */
/* It now returns a PyModuleDef instance instead of a PyModule instance. */

/* WARNING: Use PyImport_AppendInittab("pysolver_cyhook", PyInit_pysolver_cyhook) instead of calling PyInit_pysolver_cyhook directly from Python 3.5 */
PyMODINIT_FUNC PyInit_pysolver_cyhook(void);

#if PY_VERSION_HEX >= 0x03050000 && (defined(__GNUC__) || defined(__clang__) || defined(_MSC_VER) || (defined(__cplusplus) && __cplusplus >= 201402L))
#if defined(__cplusplus) && __cplusplus >= 201402L
[[deprecated("Use PyImport_AppendInittab(\"pysolver_cyhook\", PyInit_pysolver_cyhook) instead of calling PyInit_pysolver_cyhook directly.")]] inline
#elif defined(__GNUC__) || defined(__clang__)
__attribute__ ((__deprecated__("Use PyImport_AppendInittab(\"pysolver_cyhook\", PyInit_pysolver_cyhook) instead of calling PyInit_pysolver_cyhook directly."), __unused__)) __inline__
#elif defined(_MSC_VER)
__declspec(deprecated("Use PyImport_AppendInittab(\"pysolver_cyhook\", PyInit_pysolver_cyhook) instead of calling PyInit_pysolver_cyhook directly.")) __inline
#endif
static PyObject* __PYX_WARN_IF_PyInit_pysolver_cyhook_INIT_CALLED(PyObject* res) {
  return res;
}
#define PyInit_pysolver_cyhook() __PYX_WARN_IF_PyInit_pysolver_cyhook_INIT_CALLED(PyInit_pysolver_cyhook())
#endif

#endif /* !__PYX_HAVE__CyRK__cy__pysolver_cyhook */
