# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: MacOS Tests

on: [push, pull_request, workflow_dispatch]

jobs:

  test-macos:
    defaults:
      run:
        shell: bash -el {0}

    name: Test CyRK on MacOS
    runs-on: macos-latest
    strategy:
      matrix:
        python-version:
          - "3.8"
          - "3.9"
          - "3.10"
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: cyrk_test
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          auto-activate-base: false
      - name: Conda info
        shell: bash -el {0}
        run: conda info
      - name: install libomp
        shell: bash -el {0}
        run: |
          brew install libomp
          export CC=/usr/bin/clang
          export CXX=/usr/bin/clang++
          export CPPFLAGS="$CPPFLAGS -Xpreprocessor -fopenmp"
          export CFLAGS="$CFLAGS -I/usr/local/opt/libomp/include"
          export CXXFLAGS="$CXXFLAGS -I/usr/local/opt/libomp/include"
          export LDFLAGS="$LDFLAGS -Wl,-rpath,/usr/local/opt/libomp/lib -L/usr/local/opt/libomp/lib -lomp"
      - name: Install Dependencies
        shell: bash -el {0}
        run: |
          conda install numpy scipy cython llvm-openmp pytest
      - name: Install package
        shell: bash -el {0}
        run: |
          python -m pip install . -v
      - name: Run pytest
        shell: bash -el {0}
        run: pytest -v Tests/
