# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: MacOS Tests

on: [push, pull_request, workflow_dispatch]

jobs:

  test-macos:
    name: Test CyRK on MacOS
    runs-on: macos-latest
    strategy:
      matrix:
        python-version:
          - "3.8"
          - "3.9"
          - "3.10"
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Initialize conda
        run: |
          $CONDA/bin/conda init zsh
          source ~/.zshrc
          echo "$SHELL"
      - name: Install Dependencies
        run: |
          $CONDA/bin/conda create -n cyrk-dev -c conda-forge python=${{ matrix.python-version }} numpy scipy cython llvm-openmp
          $CONDA/bin/conda activate cyrk-dev
          python -m pip install --upgrade pip
          python -m pip install pytest
      - name: Install package
        run: |
          python -m pip install . -v

      - name: Run pytest
        run: pytest -v Tests/
